name: Publish Image

on:
  push:
    branches: [ master ]
    tags: [ v* ]

env:
  IMAGE_NAME: hadoop-single-node

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop_version: ['3.3.0', '2.10.0']
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push image for Hadoop v${{ matrix.hadoop_version }}
        uses: docker/build-push-action@v1
        with:
          path: ./single_node/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sdabhi23/hadoop-single-node
          add_git_labels: true
          build_args: TYPE=prod,HADOOP_VERSION=${{ matrix.hadoop_version }}
          tags: ${{ matrix.hadoop_version }}
          push: true
