name: Publish Image

on:
  push:
    branches: [ master ]
    tags: [ v* ]

env:
  IMAGE_NAME: hadoop-single-node

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hadoop_version: ['3.3.0', '2.10.0']
    steps:

      - name: Get current date
        id: labels
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image for Hadoop v${{ matrix.hadoop_version }}
        uses: docker/build-push-action@v2
        with:
          context: ./single_node/
          file: ./single_node/Dockerfile
          labels: |
            org.opencontainers.image.source="https://github.com/sdabhi23/hadoop-k8s"
            org.opencontainers.image.revision="${{ github.sha }}"
            org.opencontainers.image.created="${{ steps.labels.outputs.timestamp }}"
          build-args: |
            TYPE=prod
            HADOOP_VERSION=${{ matrix.hadoop_version }}
          tags: |
            sdabhi23/hadoop-single-node:${{ matrix.hadoop_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: user/app
